### PR TITLE
Build the book - 19.04.2023

### PR DESCRIPTION
**Pull request by DrMattG**

### CODE REVIEW

**Comment by DrMattG** [comment]
Can you just approve this - I am rendering the book again with those changes we made (I just need a reviewers approval to finialise it!)

**Comment by HannoSandvik** [comment]
I definitely approve this

**Comment by HannoSandvik** [comment]
perhaps i shouldn't have closed this?

**Review by HannoSandvik — APPROVED** [review]
NOW i definitely approve this

**Pull request merged**
