### PR TITLE
functional plant indicators_wetland

### PR DESCRIPTION
**Pull request by joatop**

### CODE REVIEW

**Comment by joatop** [comment]
wetland markdown er ikke funksjonell enda, men jeg ville gå over fra den fork'en jeg laget til å jobbe i branches her

**Comment by joatop** [comment]
just merge it for now, pls. I have yet to finish the markdown code.

**Comment by anders-kolstad** [comment]
FYI @joatop , CodeFactor picked up a few repeating issues that you could look at: https://www.codefactor.io/repository/github/ninanor/ecosystemcondition/pull/32#
None of these are critical, but you can check them out if you want.

**Review by anders-kolstad — APPROVED** [review]
Approving this PR. It is not operational, but does not affect any core files. Merging it will make it easier for Joachim to branch instead of working from a fork.

**Pull request merged**
