### PR TITLE
Port over to qmd. Untested chapters

### PR DESCRIPTION
**Pull request by DrMattG**
I have moved all the chapters to qmd format. I am working locally so have not tested this on the server yet (so probably best if we test before merging the pull request....just in case!) and only tested the rendering with the chapters that do not have associated data. If you "render" any of the chapters the whole book with render locally. Publishing to GH-pages is the same process as before as far as I can see.

### CODE REVIEW

**Comment by anders-kolstad** [comment]
Thanks for doing this!
To clarify, did you simply rename rmd files to get a .qmd ending?
And does _quarto.yml replace _bookdown.yml?

Those that have already started writing based on the temptae.Rmd file, would they need to do anything? Just change the file ending?

**Comment by anders-kolstad** [comment]
Is the  _book folder replacing _bookdown_files?

**Comment by DrMattG** [comment]
@anders-kolstad It looks like the Rstudio version on the server is not the same as the one we have locally!

Server:  RStudio 2021.09.2+382 "Ghost Orchid" Release (fc9e217980ee9320126e33cdf334d4f4e105dc4f, 2022-01-04) for Ubuntu Bionic
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36 Edg/108.0.1462.54

Local: RStudio 2022.12.0+353 "Elsbeth Geranium" Release (7d165dcfc1b6d300eb247738db2c7076234f6ef0, 2022-12-03) for Windows
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) RStudio/2022.12.0+353 Chrome/102.0.5005.167 Electron/19.1.3 Safari/537.36

This is why Quarto will not run. 

I guess we need to ask for an update to the Rstudio version on the server..... ?

**Comment by anders-kolstad** [comment]
I can ask. I actually asked just before Christmas, and Kjetil replied:

Vi har planer om å oppdatere Rstudio på nyåret da dagens versjon begynner å bli gammel, men ser at du har funnet det du trenger så da er det ikke så mye hast for deg.
I will ask again.

A

**Comment by DrMattG** [comment]
I will close this for now and re-open a pull request at a later stage

**Pull request closed without merging**
