### PR TITLE
Insect take 2

### PR DESCRIPTION
**Pull request by jenast**
I've added the genetic diversity and alien species indicator calculations. Recalculated all NorIns indicators with 5 year rolling windows, and made some text clean-ups.
Also exported the indicators, but in a long format (all values in one column, with year indicated by a separate column) instead of wide (yearly values in separate columns).

I think everything is included now, so this could be the last pull request.

### CODE REVIEW

**Comment by anders-kolstad** [comment]
There are 164 files changes, most of which do not relate to this branch. I think we need to do a `git merge`, or possibly move the real changes over into a new branch. 

I also cannot find the `insectIndicators.Rmd` file, only the draft version. Did you write in `DRAFT_insectIndicators.Rmd`?

Great that you wrote the indicator maps to file, but I think we can refrain from storing these on github. It's enough that we have demonstrated the workflow.

Let's talk next week.

**Comment by jenast** [comment]
Kanskje enklest at jeg startet en ny oppdatert branch, og flytter over mine endringer dit. Jeg har bare skrivit i en fil. Kan også skippe DRAFT_ hvis det passer bedre.

**Comment by anders-kolstad** [comment]
Ja gjerne det. Det ligger allerede en fil der: https://github.com/NINAnor/ecosystemCondition/blob/main/insectIndicators.Rmd 
Kanskje du kan oppdatere den?

**Comment by jenast** [comment]
Ok, legger opp en ny snart

**Pull request closed without merging**
